def instruction():
    print('Args:')
    print('    args: get the command line script.')
    print('          The command we have 10 types as following:')
    print()
    print('          0.  --args                  show all args and directions.')
    print()
    print('          1.  --upload                upload status (boolean).')
    print('          2.  --download              download status (boolean).')
    print()
    print('          upload state command line script(must provides if your choose upload):')
    print('          3.  --images-folder:        upload images folder path.')
    print('          4.  --xml-zip:              upload annotations XML zip path.')
    print('          5.  --task-name:            upload the task name what your wanna create.')
    print('          6.  --project-name:         upload the task belong to which project.')
    print()
    print('          download state command line script(must provides if your choose download):')
    print('          6.  --project-name:         download the task belong to which project.')
    print('          7.  --task-id:              download the task what id is.')
    print()
    print('          no must need to provide the script:')
    print('          8.  --api-path:             provide the url')
    print('                                      default is "http://10.0.13.80:8080/api/v1/"')
    print('          9.  --annotation-format:    the task annotation format, ')
    print('                                      default is "PASCAL%20VOC%201.1" (PASCAL VOC 1.1)')
    print('                                      because http parser blank is "%20"')
